/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as CrossSectionRouteImport } from './routes/cross-section'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SurveysRouteImport } from './routes/surveys'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const CrossSectionRoute = CrossSectionRouteImport.update({
  id: '/cross-section',
  path: '/cross-section',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cross-section': typeof CrossSectionRoute
  '/data-sources': typeof DataSourcesRoute
  '/explorer': typeof ExplorerRoute
  '/interventions': typeof InterventionsRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/surveys': typeof SurveysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cross-section': typeof CrossSectionRoute
  '/data-sources': typeof DataSourcesRoute
  '/explorer': typeof ExplorerRoute
  '/interventions': typeof InterventionsRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/surveys': typeof SurveysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/cross-section': typeof CrossSectionRoute
  '/data-sources': typeof DataSourcesRoute
  '/explorer': typeof ExplorerRoute
  '/interventions': typeof InterventionsRoute
  '/monitoring': typeof MonitoringRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/surveys': typeof SurveysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/cross-section'
    | '/data-sources'
    | '/explorer'
    | '/interventions'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/surveys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/cross-section'
    | '/data-sources'
    | '/explorer'
    | '/interventions'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/surveys'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/cross-section'
    | '/data-sources'
    | '/explorer'
    | '/interventions'
    | '/monitoring'
    | '/reports'
    | '/settings'
    | '/surveys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  CrossSectionRoute: typeof CrossSectionRoute
  DataSourcesRoute: typeof DataSourcesRoute
  ExplorerRoute: typeof ExplorerRoute
  InterventionsRoute: typeof InterventionsRoute
  MonitoringRoute: typeof MonitoringRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SurveysRoute: typeof SurveysRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cross-section': {
      id: '/cross-section'
      path: '/cross-section'
      fullPath: '/cross-section'
      preLoaderRoute: typeof CrossSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  CrossSectionRoute: CrossSectionRoute,
  DataSourcesRoute: DataSourcesRoute,
  ExplorerRoute: ExplorerRoute,
  InterventionsRoute: InterventionsRoute,
  MonitoringRoute: MonitoringRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SurveysRoute: SurveysRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
